language: python
python:
  - "3.9"
os:
  - linux

git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR=examples/native-blink


install:
  - pip install platformio
  - pio platform install file://.

script:
  - pio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
